name: Carter

on:
  push:
    paths:
      - '**'
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
        
      - name: Set DB_URL for CI
        run: echo "DB_URL=jdbc:postgresql://postgres:5432/postgres" >> $GITHUB_ENV

      - name: Wait for Postgres to be ready
        run: |
          for i in {1..20}; do
            if pg_isready -h postgres -U postgres -p 5432; then
              echo "PostgreSQL is ready!";
              exit 0;
            fi
            echo "Waiting for PostgreSQL... attempt $i";
            sleep 5;
          done
          echo "PostgreSQL failed to start after 100 seconds";
          exit 1

      - name: Build With Maven
        run: ./mvnw -ntp verify
