name: Carter

on:
  push:
    paths:
      - '**'
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 15433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Wait for Postgres to be ready
        run: |
          until pg_isready -h postgres -p 5432; do
            echo "Waiting for PostgreSQL...";
            sleep 2;
          done

      - name: Build With Maven
        run: ./mvnw -ntp verify
